name: Build, Release Docker Image, and Deploy to Heroku

on:
  push:
    tags:         # Trigger the workflow only when a tag is pushed
      - 'v*'      # Only trigger for tags starting with "v" (e.g., v1.0.0, v2.1.3)

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Set this in your repository secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Set this in your repository secrets

      # Step 3: Extract the GitHub tag
      - name: Extract GitHub tag
        id: extract_tag
        run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      # Step 4: Build the Docker image with tags
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ltltutor:latest \
                       -t ${{ secrets.DOCKER_USERNAME }}/ltltutor:${{ env.TAG }} .

      # Step 5: Push the Docker image to DockerHub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/ltltutor:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ltltutor:${{ env.TAG }}

      # Step 6: Log in to Heroku Container Registry
      - name: Log in to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}  # Set this in your repository secrets
        run: |
          echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com

      # Step 7: Tag and push the Docker image to Heroku
      - name: Push Docker image to Heroku
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/ltltutor:latest registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
          docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

      # Step 8: Release the Docker image on Heroku
      - name: Release Docker image on Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}