name: Run Unit Tests

on:
  pull_request:
    branches:
      - main  # Run tests on pull requests targeting the 'main' branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Check out code
      uses: actions/checkout@v3

    # Step 2: Install Java (required for ANTLR)
    - name: Install Java
      run: |
        sudo apt-get update
        sudo apt-get install -y default-jre

    # Step 3: Install ANTLR
    - name: Install ANTLR
      run: |
        curl -O https://www.antlr.org/download/antlr-4.13.0-complete.jar
        export CLASSPATH=".:$(pwd)/antlr-4.13.0-complete.jar:$CLASSPATH"
        alias antlr4='java -jar $(pwd)/antlr-4.13.0-complete.jar'

    # Step 4: Generate parser and lexer files
    - name: Generate ANTLR files
      working-directory: ./src
      run: |
        antlr4 -Dlanguage=Python3 ltl.g4

    # Step 5: Install pip dependencies
    - name: Install pip dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    # Step 6: Run unittests
    - name: Run unittests
      run: |
        export TEST_MODE=true
        python -m unittest discover -s test -p "test_*.py"